services:
  # Hệ thống nguồn (EMR Source Database)
  emr-db:
    image: postgres:15-alpine
    container_name: emr-postgres
    restart: always
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: his_db
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres_data:/var/lib/postgresql/data
      - ./emr-provider-system/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: emr-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Cổng giao tiếp dữ liệu
      - "15672:15672" # Cổng giao diện quản lý (Management UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Hệ thống đích (FHIR Store)
  fhir-store:
    image: mongo:latest
    container_name: emr-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./infrastructure/mongo_data:/data/db

  debezium:
    image: quay.io/debezium/server:2.4
    container_name: emr-debezium
    restart: always
    depends_on:
      - emr-db
      - rabbitmq
    volumes:
      - ./infrastructure/debezium_conf:/debezium/conf
      - ./infrastructure/debezium_data:/debezium/data

  # Công cụ xem dữ liệu MongoDB 
  mongo-express:
    image: mongo-express
    container_name: emr-mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: fhir-store
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123

  # HAPI FHIR Server R5 — FHIR REST API chuẩn HL7
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      hapi.fhir.fhir_version: R5
      hapi.fhir.allow_multiple_delete: "true"
      hapi.fhir.allow_external_references: "true"
      hapi.fhir.reuse_cached_search_results_millis: "5000"
    networks:
      - default

  prometheus:
      image: prom/prometheus:latest
      container_name: fhir_prometheus
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      # Quan trọng: Prometheus cần nằm chung mạng với các dịch vụ khác
      networks:
        - default

  grafana:
    image: grafana/grafana:latest
    container_name: fhir_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - default

networks:
  default:
    name: emr-fhir-network
