global:
  scrape_interval: 5s # 5 giây lấy dữ liệu một lần (để demo cho nhanh)

scrape_configs:
  - job_name: 'fhir-adapter'
    static_configs:
      # Thay '192.168.1.x' bằng IP máy em hoặc 'host.docker.internal'
      - targets: ['host.docker.internal:8008']
