# Database Configuration
DATABASE_URL = "postgresql://admin:password123@localhost:5432/his_db"

# RabbitMQ Configuration
RABBITMQ_HOST = "localhost"
RABBITMQ_QUEUE_NAME = "emr_events"
RABBITMQ_DELIVERY_MODE = 2  # Persistent message

# Event Types
EVENT_PATIENT_CREATED = "PATIENT_CREATED"
EVENT_PATIENT_UPDATED = "PATIENT_UPDATED"
EVENT_PATIENT_DELETED = "PATIENT_DELETED"
EVENT_ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
EVENT_ENCOUNTER_UPDATED = "ENCOUNTER_UPDATED"
EVENT_OBSERVATION_CREATED = "OBSERVATION_CREATED"
EVENT_PRACTITIONER_CREATED = "PRACTITIONER_CREATED"

# API Configuration
API_TITLE = "HIS Prototype API"

# Field Length Limits
MAX_LENGTH_PRACTITIONER_CODE = 20
MAX_LENGTH_FULL_NAME = 100
MAX_LENGTH_SPECIALTY = 100
MAX_LENGTH_PHONE = 20
MAX_LENGTH_PATIENT_EXTERNAL_ID = 50
MAX_LENGTH_NATIONAL_ID = 12
MAX_LENGTH_INSURANCE_CARD_NO = 15
MAX_LENGTH_GENDER = 10
MAX_LENGTH_STATUS = 20
MAX_LENGTH_LOCATION = 100
MAX_LENGTH_CATEGORY = 50
MAX_LENGTH_CODE_DISPLAY = 100
MAX_LENGTH_CODE_SYSTEM = 100
MAX_LENGTH_VALUE_UNIT = 20

# Gender Values
GENDER_MALE = "male"
GENDER_FEMALE = "female"
GENDER_OTHER = "other"
GENDER_CHOICES = [GENDER_MALE, GENDER_FEMALE, GENDER_OTHER]

# Encounter Status Values
ENCOUNTER_STATUS_PLANNED = "planned"
ENCOUNTER_STATUS_ARRIVED = "arrived"
ENCOUNTER_STATUS_FINISHED = "finished"
ENCOUNTER_STATUS_CHOICES = [
    ENCOUNTER_STATUS_PLANNED,
    ENCOUNTER_STATUS_ARRIVED,
    ENCOUNTER_STATUS_FINISHED,
]
DEFAULT_ENCOUNTER_STATUS = ENCOUNTER_STATUS_FINISHED

# Observation Categories
OBSERVATION_CATEGORY_VITAL_SIGNS = "vital-signs"
OBSERVATION_CATEGORY_LABORATORY = "laboratory"
