# Database Configuration
DATABASE_URL = "postgresql://admin:password123@localhost:5432/his_db"

# RabbitMQ Configuration
RABBITMQ_HOST = "localhost"
RABBITMQ_QUEUE_NAME = "emr_events"
RABBITMQ_DELIVERY_MODE = 2  # Persistent message

# Event Types
EVENT_PATIENT_CREATED = "PATIENT_CREATED"
EVENT_PATIENT_UPDATED = "PATIENT_UPDATED"
EVENT_PATIENT_DELETED = "PATIENT_DELETED"
EVENT_ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
EVENT_ENCOUNTER_UPDATED = "ENCOUNTER_UPDATED"
EVENT_OBSERVATION_CREATED = "OBSERVATION_CREATED"
EVENT_PRACTITIONER_CREATED = "PRACTITIONER_CREATED"

# API Configuration
API_TITLE = "HIS Prototype API (QD-130)"
API_HOST = "localhost"
API_PORT = 8000
API_BASE_URL = f"http://{API_HOST}:{API_PORT}"

# API Endpoints
ENDPOINT_BENH_NHAN = "/benh-nhan/"
ENDPOINT_NHAN_VIEN_Y_TE = "/nhan-vien-y-te/"
ENDPOINT_DOT_DIEU_TRI = "/dot-dieu-tri/"
ENDPOINT_CHI_TIET_THUOC = "/chi-tiet-thuoc/"
ENDPOINT_DICH_VU_KY_THUAT = "/dich-vu-ky-thuat/"
ENDPOINT_CAN_LAM_SANG = "/can-lam-sang/"
ENDPOINT_DIEN_BIEN_LAM_SANG = "/dien-bien-lam-sang/"

# Field Length Limits (theo QĐ-130)
MAX_LENGTH_MA_BAC_SI = 255
MAX_LENGTH_HO_TEN = 255
MAX_LENGTH_CHUYEN_KHOA = 255
MAX_LENGTH_PHONE = 20
MAX_LENGTH_MA_BN = 100
MAX_LENGTH_CCCD = 15
MAX_LENGTH_MA_THE_BHYT = 15
MAX_LENGTH_MA_DKBD = 5
MAX_LENGTH_MA_LK = 100
MAX_LENGTH_NATIONAL_ID = 15

# Gender Values (1: Nam, 2: Nữ, 3: Không xác định)
GENDER_MALE = 1
GENDER_FEMALE = 2
GENDER_UNKNOWN = 3
GENDER_CHOICES = [GENDER_MALE, GENDER_FEMALE, GENDER_UNKNOWN]

